### ISSUE TITLE
CGMES Current limits conversion failed 

### ISSUE THREAD

**Issue by annetill** [powsybl/powsybl-core#1371]
* **Do you want to request a *feature* or report a *bug*?**

A bug, on Elia and NGESO network. CGMES conversion failed because of current limits import.

* **What is the current behavior?**

````Loading network '/media/sf_powsybl-data/IOP20200212+boundaries/IOP20200212/IE00_BD12022020_1D_EIRGRIDSONI_Nodebreaker/20200212_1030_FO3_IE1.zip'
java.lang.IndexOutOfBoundsException: position (0) must be less than the number of elements that remained (0)
	at com.google.common.collect.Iterators.get(Iterators.java:801)
	at com.google.common.collect.Iterables.get(Iterables.java:729)
	at com.powsybl.cgmes.conversion.CurrentLimitsMapping.addAll(CurrentLimitsMapping.java:38)
	at com.powsybl.cgmes.conversion.Conversion.convert(Conversion.java:187)
	at com.powsybl.cgmes.conversion.CgmesImport.importData(CgmesImport.java:105)
	at com.powsybl.iidm.import_.Importer.importData(Importer.java:65)
	at com.powsybl.iidm.import_.Importers.loadNetwork(Importers.java:390)
	at com.powsybl.iidm.import_.Importers.loadNetwork(Importers.java:396)
	at com.rte_france.powsybl.cgmes.validation.ComparisonSvTool.run(ComparisonSvTool.java:146)
	at com.powsybl.tools.CommandLineTools.run(CommandLineTools.java:164)
	at com.powsybl.tools.Main.main(Main.java:29)
````

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Indeed we just have a NaN as PATL and no TATL to give a approximation of the PATL. As the PATL is mandatory, we are looking for an approximation.

* **What is the expected behavior?**

Do not import limits when we have nothing at all. 

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by MioRtia** [comment]
Resolved by #1372
