### ISSUE TITLE
PSS/E unexpected end of file

### ISSUE THREAD

**Issue by geofjamg** [powsybl/powsybl-core#1621]
* **Do you want to request a *feature* or report a *bug*?**

Bug possibly related to #1620 

* **What is the current behavior?**
I tried to import a version 32 raw file and end up with an exception:
```bash
Exception in thread "main" com.powsybl.psse.model.PsseException: Unexpected end of file
	at com.powsybl.psse.model.io.RecordGroupIOLegacyText.skip(RecordGroupIOLegacyText.java:92)
	at com.powsybl.psse.model.pf.io.PowerFlowRawData33.read(PowerFlowRawData33.java:58)
	at com.powsybl.psse.converter.PsseImporter.importData(PsseImporter.java:135)
	at com.powsybl.iidm.import_.Importer.importData(Importer.java:65)
	at com.powsybl.iidm.import_.Importers.loadNetwork(Importers.java:438)
	at com.powsybl.iidm.import_.Importers.loadNetwork(Importers.java:454)
	at com.powsybl.iidm.import_.Importers.loadNetwork(Importers.java:469)
	at com.powsybl.iidm.import_.Importers.loadNetwork(Importers.java:479)
```
This is because an inducation machine section is expected but not present in the file. Maybe this is because induction machine have been added to 33?

```
0 / END OF SWITCHED SHUNT DATA, BEGIN GNE DATA
0 / END OF GNE DATA
Q
```

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by geofjamg** [comment]
Fixed in #1626
