### ISSUE TITLE
CGMES export Bug 

### ISSUE THREAD

**Issue by AnkurArohi** [powsybl/powsybl-core#2713]
### Describe the current behavior

When two networks are merged and then the merged network is tried to be exported in CGMES format, this is the exception 

java.lang.NullPointerException: null
        at com.powsybl.cgmes.conversion.NamingStrategy$Identity.getCgmesId(NamingStrategy.java:72)
        at com.powsybl.cgmes.conversion.export.TopologyExport.writeConnectableTerminals(TopologyExport.java:68)
        at com.powsybl.cgmes.conversion.export.TopologyExport.writeTerminals(TopologyExport.java:54)
        at com.powsybl.cgmes.conversion.export.TopologyExport.write(TopologyExport.java:46)
        at com.powsybl.cgmes.conversion.CgmesExport.export(CgmesExport.java:98)
        at com.powsybl.iidm.network.Network.write(Network.java:1248)
        at com.powsybl.iidm.network.Network.write(Network.java:1269)
        at com.powsybl.python.network.NetworkCFunctions.lambda$dumpNetwork$7(NetworkCFunctions.java:185)
        at com.powsybl.python.commons.Util.doCatch(Util.java:56)

### Describe the expected behavior

There should not be any such exception and if there is such an exception regarding any missing value, the exception should try to mention it 

### Describe the steps

- Load a DSO network with boundary files
- Load TSO network with boundary files
- Check if the dangling lines df has the boundariesin both DSO and TSO
- Deactivate the DSO voltage levels which are actually duplicates from TSO 
- Merge both the networks
- Check the get_lines DF, it should have the dangling lines boundaries merged
- Export to CGMES 

### Environment

- pypowsybl

**Comment by AnkurArohi** [comment]
this seems to work thanks @zamarrenolm
