### ISSUE TITLE
AFS does not handle accent properly

### ISSUE THREAD

**Issue by mathbagu** [powsybl/powsybl-core#322]
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: 
```
/home/baguemat/Mod��les
	at sun.nio.fs.UnixPath.encode(UnixPath.java:147)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
	at com.powsybl.afs.local.storage.LocalAppStorage.nodeIdToPath(LocalAppStorage.java:113)
```

**Comment by geofjamg** [comment]
What could be done for this issue? Unmappable character seems not to be supported in underlying nio2 library.

**Comment by geofjamg** [comment]
AFS is not anymore part of core
