### ISSUE TITLE
Some legit calculated time-series can't be computed

### ISSUE THREAD

**Issue by jonenst** [powsybl/powsybl-core#656]
The following test
```java
    @Test
    public void hugebuilderTest() {                                                         
        int iterCount = 3000;                                                               
        DoubleTimeSeries a = TimeSeries.createDouble("a", IrregularTimeSeriesIndex.create(Instant.now()), 5d);
        DoubleTimeSeries b = DoubleTimeSeries.fromTimeSeries(a)
            .build(
                "ts['b'] = ts['a']",
                "for (i=0; i<"+iterCount+"; i++) { ts['b'] = ts['b'] + 1 }"                 
            ).get(0) ;                                                                      
        assertArrayEquals(new double[] {5d+iterCount}, b.toArray(), 0d);                    
    }   
```
errors with
```
java.lang.StackOverflowError
	at com.powsybl.timeseries.ast.DefaultNodeCalcVisitor.visit(DefaultNodeCalcVisitor.java:35)
	at com.powsybl.timeseries.ast.BinaryOperation.accept(BinaryOperation.java:122)
	at com.powsybl.timeseries.ast.DefaultNodeCalcVisitor.visit(DefaultNodeCalcVisitor.java:36)
	at com.powsybl.timeseries.ast.BinaryOperation.accept(BinaryOperation.java:122)
```

It should work. Reported in https://github.com/powsybl/powsybl-core/pull/629 but this issue is about making it work, not about correctly handling the error.

**Comment by rolnico** [comment]
This bug is not present anymore (version 7.0.1), probably since the PR #980.
